### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Akanshu9990** [juspay/hyperswitch-control-center#43]
after running npm run start,
{ static:
   { directory: '/home/ubuntu/hyperswitch-control-center/dist/hyperswitch' },
  compress: true,
  hot: true,
  port: 9000,
  historyApiFallback: true,
  proxy: {},
  onBeforeSetupMiddleware: [Function: onBeforeSetupMiddleware] }
(node:21272) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
[webpack-cli] /home/ubuntu/hyperswitch-control-center/node_modules/webpack-dev-server/lib/servers/WebsocketServer.js:10
  static heartbeatInterval = 1000;
                           ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Server.getServerTransport (/home/ubuntu/hyperswitch-control-center/node_modules/webpack-dev-server/lib/Server.js:1758:28)
    at Server.createWebSocketServer (/home/ubuntu/hyperswitch-control-center/node_modules/webpack-dev-server/lib/Server.js:2569:57)
    at Server.start (/home/ubuntu/hyperswitch-control-center/node_modules/webpack-dev-server/lib/Server.js:3384:12)
npm ERR! code ELIFECYCLE

**Comment by dvenga** [comment]
Please check with the latest version of node (version 16 or above) and try again.
